name: freezed_example
description: example
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  equatable: any
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1
flutter:
  uses-material-design: true
